### ISSUE TITLE
cf7 app manifest schema for services list not documented

### ISSUE THREAD

**Issue by basinilya** [cloudfoundry/docs-dev-guide#430]
From: https://docs.cloudfoundry.org/devguide/services/application-binding.html#arbitrary-params-binding

> Arbitrary parameters are supported in app manifests in cf CLI v7.0 and later.

I managed to get some information on the new syntax from the [SO answer](https://stackoverflow.com/a/66063124/447503). `services` was a list of strings, but now it's a list of strings or maps where a map can contain at least the properties `name` and `parameters`

Please update https://github.com/cloudfoundry/docs-dev-guide/blob/37ab5e64814cd46470e7c21e45eecc9912c28373/deploy-apps/manifest-attributes.html.md.erb#L534

**Comment by anita-flegg** [comment]
@Gerg, @ameowlia, Would you mind suggesting a reviewer for this issue before I implement the changes? Thanks :)

**Comment by philippthun** [comment]
@anita-flegg I could review the changes to the manifest attributes docs from CAPI side.

Besides what is mentioned in the linked stack overflow answer, there is also an optional `binding_name` attribute.

So the following `services` attributes are possible:
```
services:
  - service-1
  - name: service-2
  - name: service-3
    parameters:
      key-1: value-1
      key-2: [value-2, value-3]
      key-3: ... any other kind of value ...
  - name: service-4
    binding_name: binding-1
```
